main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import contactView, successView

app_name = 'main'

urlpatterns = [
                  path('', views.HomeView.as_view(), name='home_url'),
                  path('contact/', contactView, name='contact_url'),
                  path('<slug:slug>/', views.ProductDetail.as_view(), name='productdetail_url'),
                  path('success/', successView, name='success_url'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from ckeditor.fields import RichTextField
from django_resized import ResizedImageField
from django.db import models
from mapbox_location_field.models import LocationField


class SomeLocationModel(models.Model):
    location = LocationField(map_attrs={
        "zoom": 7,
        "center": [41.26848144933652, 69.22686929378176],
        "cursor_style": 'pointer',
        "marker_color": "red",
        "rotate": True,
        "geocoder": True,
        "fullscreen_button": True,
        "navigation_buttons": True,
        "track_location_button": True,
        "readonly": True,
        "placeholder": "Pick a location on map below",
    })


class Header(models.Model):
    title = models.CharField(max_length=100)
    image = ResizedImageField(size=[1280, 860], crop=['middle', 'center'], upload_to='uploads/home/%Y/%m/%d')
    image_second = ResizedImageField(size=[1280, 860], crop=['middle', 'center'], upload_to='uploads/home/%Y/%m/%d')
    image_third = ResizedImageField(size=[1280, 860], crop=['middle', 'center'], upload_to='uploads/home/%Y/%m/%d')
    description = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Header'
        verbose_name_plural = 'Header'


class ProductDetail(models.Model):
    title = models.CharField(max_length=100)
    image = ResizedImageField(size=[1280, 1024], crop=['middle', 'center'], upload_to='uploads/product/%Y/%m/%d')
    slug = models.SlugField(max_length=100, unique=True)
    first_list_title = models.CharField(max_length=50, blank=True, null=True)
    first_list = RichTextField(blank=True, null=True)
    second_list_title = models.CharField(max_length=50, blank=True, null=True)
    second_list = RichTextField(blank=True, null=True)
    third_list_title = models.CharField(max_length=50, blank=True, null=True)
    third_list = RichTextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Product'
        verbose_name_plural = 'Product'

main/forms.py
from django import forms
from django.core.exceptions import ValidationError


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)


class ProductForm(forms.ModelForm):
    # Add some custom validation to our image field
    def clean_image(self):
        image = self.cleaned_data.get('image', False)
        if image:
            if image. _size > 2*1024*1024:
                raise ValidationError("Image file too large ( > 4mb )")
            return image
        else:
            raise ValidationError("Couldn't read uploaded image")

main/views.py
from django.views import generic
from . import models

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from task.settings import EMAIL_HOST_USER
from .forms import ContactForm


class HomeView(generic.TemplateView):
    template_name = 'pages/home/index.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['head'] = models.Header.objects.all().first()
        context['products'] = models.ProductDetail.objects.order_by('-created')[:5]
        long, lat = models.SomeLocationModel.objects.all().first().location
        context['long'] = long
        context['lat'] = lat
        return context


class ProductDetail(generic.DetailView):
    model = models.ProductDetail
    template_name = 'pages/product/product_detail.html'
    context_object_name = 'product'
    # pk_url_kwarg = 'id'


class SomeLocationModel(generic.TemplateView):
    model = models.SomeLocationModel
    template_name = 'pages/home/home_include/map.html'
    context_object_name = 'map'


def contactView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            try:
                send_mail(name, 'salom', EMAIL_HOST_USER, [email])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('main:home_url')
    return render(request, "pages/home/index.html", {'form': form})


def successView(request):
    return HttpResponse('Success! Thank you for your message.')

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no, viewport-fit=cover">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>Заголовок главной страницы</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Piazzolla:wght@400;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>


{% block content %}
{% endblock content %}


<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=28ba27e6-8179-45dd-8a90-a542e1883e67"
        type="text/javascript"></script>
<script src="{% static 'js/swiper-bundle.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/pages/home/home_include/header.html
{% load static %}ц


<h1>{{ head.title }}</h1>
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide"><img src="{{ head.image.url }}" alt="Первая картинка"></div>
        <div class="swiper-slide"><img src="{{ head.image_second.url }}" alt="Вторая картинка"></div>
        <div class="swiper-slide"><img src="{{ head.image_third.url }}" alt="Третья картинка"></div>
        {#            <div class="swiper-slide"><img src="{{ head.image }}" alt="Четвертая картинка"></div>#}
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>
<div class="intro-text{% comment %}{% endcomment %}">
    <p>{{ head.description|safe }}</p>
</div>

templates/pages/home/home_include/map.html
{% load static %}


<div id="map" data-latitude="{{ lat }}" data-longitude="{{ long }}"></div>
<h2>Отправить сообщение</h2>
<form id="form" method="post" action="{% url 'main:contact_url' %}">
    {% csrf_token %}
    <input type="text" placeholder="Ваше имя" class="text-box" id="name" name="name" onfocus="blurEvent(this)"
           onkeyup="onChangeEvent(this)">
    <input type="text" placeholder="Электронная почта" class="text-box" id="email" name="email"
           onfocus="blurEvent(this)"
           onkeyup="onChangeEvent(this)">
    <input type="submit" value="Отправить" class="button" onclick="event.preventDefault();onSubmitEvent()">
</form>

templates/pages/home/home_include/product.html
{% load static %}

<div class="products-list">
    <h2>Продукты</h2>
    {% for product in products %}
        <ul>
            <li><a href="{% url 'main:productdetail_url' product.slug %}">{{ product.title }}</a></li>
        </ul>
    {% endfor %}
</div>

templates/pages/home/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Заголовок главной страницы {% endblock title %}

{% block content %}
    <div class="wrapper">

        <div class="content">

            {% include 'pages/home/home_include/header.html' %}

            {% include 'pages/home/home_include/product.html' %}

            {% include 'pages/home/home_include/map.html' %}

        </div>
    </div>
{% endblock content %}

templates/pages/product/product_detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="wrapper">
        <div class="content">
            <a href="{% url 'main:home_url' %}" class="go-back">На главную</a>
            <h1>{{ product.title }}</h1>
            <img src="{{ product.image.url }}" alt="Какой-то продукт" class="product-image">
            <div class="product-info">
                <div class="product-info-item">
                    {% if product.first_list_title %}
                        <h2>{{ product.first_list_title }}</h2>
                    {% endif %}
                    {% if product.first_list %}
                        <ul>
                            <li>{{ product.first_list|safe }}</li>
                        </ul>
                    {% endif %}
                </div>
                <div class="product-info-item">
                    {% if product.second_list_title %}
                        <h2>{{ product.second_list_title }}</h2>
                    {% endif %}
                    {% if product.second_list %}
                        <ul>
                            <li>{{ product.second_list|safe }}</li>
                        </ul>
                    {% endif %}
                </div>
                <div class="product-info-item">
                    {% if product.third_list_title %}
                        <h2>{{ product.third_list_title }}</h2>
                    {% endif %}
                    {% if product.third_list %}
                        <ul>
                            <li>{{ product.third_list|safe }}</li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}